### PR TITLE
Fix xen

### PR DESCRIPTION
**Pull request by iusyk**
The branch of xen has been changed from master to prod_aos. 
Source inc.xen-version.inc

### CODE REVIEW

**Comment by rshym** [comment]
It's good idea before submitting PR to do following:
```
git fetch --all --prune
git checkout master
git pull <upstream_remote> master
```
Only after that create or rebase your branch.

In this case there will be no merge of 'master' with already existing patches.

**Comment by iusyk** [comment]
> It's good idea before submitting PR to do following:
> 
> ```
> git fetch --all --prune
> git checkout master
> git pull <upstream_remote> master
> ```
> 
> Only after that create or rebase your branch.
> 
> In this case there will be no merge of 'master' with already existing patches.

you are rigtht

**Comment by rshym** [comment]
More important point, that we need to discuss inside team - do we need to create product specific branches in xen for every product that we do?

**Comment by iusyk** [comment]
> It's good idea before submitting PR to do following:
> 
> ```
> git fetch --all --prune
> git checkout master
> git pull <upstream_remote> master
> ```
> 
> Only after that create or rebase your branch.
> 
> In this case there will be no merge of 'master' with already existing patches.

this is what i did, but there were some conflicts

**Pull request closed without merging**
