### PR TITLE
domd: network: Separate cetibox related configs

### PR DESCRIPTION
**Pull request by rshym**
Cetibox has special network configuration with VLANs.
This requires not only dedicated config files but also
eth0.network need to be changed.
This is the reason to have board specific folder with
cetibox related network configs.

This patch assumes that eth0.network is removed from guest addons.

Related commits for reference:
8f96b8a domd: Configure ethernet switch ports and VLANs
b26f482 domd: Use eth0.network from systemd recipe
9c4d3f3 domd cetibox: remove eth0.network from guest-addons

Signed-off-by: Ruslan Shymkevych <ruslan.shymkevych@gmail.com>

### CODE REVIEW

**Comment by rshym** [comment]
I'' be glad to see opinions on which option is better to use in systemd_%.bbappend:
1) `install -m 0644 ${WORKDIR}/eth0.*.net*  ${D}${sysconfdir}/systemd/network/`
or
2) list all four files explicitly: eth0.1.network, eth0.1.netdev, eth0.2.network, eth0.2.netdev.

**Comment by rshym** [comment]
Fixed email in commit message.

**Comment by lorc** [comment]
> I'll be glad to see opinions on which option is better to use in systemd_%.bbappend:

I'd prefer the second option. With that:

`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by rshym** [comment]
Comment is addressed: eth0.?.net* files are listed explicitly.
Reviewer is added.

**Pull request merged**
