### PR TITLE
Update INSTALL.md and remove INSTALL.txt

### PR DESCRIPTION
**Pull request by rshym**

### CODE REVIEW

**Comment by lorc** [comment]
Hi @rshym , I don't like idea of patch that copies and modifies file in the same time.
I believe it should be done in two separate patches:

 - Rename INSTALL.md to README.md and then update README.md 
or 
 - Update INSTALL.md and then rename it to README.md. 

In the second case you can also delete INSTALL.txt in the same patch.

**Comment by lorc** [comment]
Also, regarding README.md itself: I believe, that every  README should begin with the description of the project. E.g. why someone need it at all. How to build it - it is not important.

So maybe it is better to just update INSTALL.md, remove INSTALL.txt and write README.md from scratch? Something like "meta-xt-prod-aos is the meta layer for Xen Troops build system. It provides the complete set of recipes to build the AOS-enabled virtual machine along with the full set of XT distributive for RCar Gen3 platform: Xen hypervisor, dom0, domd and domf (AOS VM itself). For build instructions please see INSTALL.md".

I believe, AOS owner can correct the example above and even provide the better description.

**Comment by rshym** [comment]
Thanks, I agree that this will be much better approach. I will rework these patches.

**Comment by rshym** [comment]
Comments are addressed.
INSTALL.md is far from state when it may be called readme, so:
- no renaming to readme, just update install.md
- install.txt is removed as outdated copy-paste from other project

**Comment by rshym** [comment]
Reviewer added.

**Pull request merged**
